# Generated by Django 5.0.7 on 2024-07-24 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/')),
                ('title', models.CharField(max_length=255)),
                ('product_id', models.CharField(max_length=255, unique=True)),
                ('price', models.CharField(max_length=250)),
                ('tag', models.CharField(max_length=25)),
                ('colors', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
