# Generated by Django 5.0.7 on 2024-07-25 09:44

import jsonfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0002_remove_product_colors'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='colors',
            field=jsonfield.fields.JSONField(default=1),
            preserve_default=False,
        ),
    ]
