# Generated by Django 5.0.7 on 2024-07-25 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0005_size_product_sizes'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='design',
            field=models.CharField(default=1, max_length=400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='fit',
            field=models.CharField(default=1, max_length=400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='neck',
            field=models.CharField(default=1, max_length=400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='occasion',
            field=models.CharField(default=1, max_length=400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='sleeve',
            field=models.CharField(default=1, max_length=400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='wash_care',
            field=models.CharField(default=1, max_length=400),
            preserve_default=False,
        ),
    ]
