# Generated by Django 5.0.7 on 2024-07-26 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0011_product_color_product_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(max_length=225),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(max_length=225),
        ),
    ]
