# Generated by Django 5.0.7 on 2024-07-26 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0012_alter_product_color_alter_product_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
    ]
