# Generated by Django 5.0.7 on 2024-08-04 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0018_magazine'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo1', models.ImageField(upload_to='shop/')),
                ('photo2', models.ImageField(upload_to='shop/')),
                ('photo3', models.ImageField(upload_to='shop/')),
                ('name', models.CharField(max_length=255)),
                ('product_id', models.CharField(max_length=255, unique=True)),
                ('color', models.CharField(max_length=225)),
                ('size', models.CharField(max_length=225)),
                ('price', models.CharField(max_length=250)),
                ('cat', models.CharField(max_length=25)),
            ],
        ),
    ]
