# Generated by Django 5.0.7 on 2024-09-04 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0022_shop_gen'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='design',
            field=models.CharField(default=1, max_length=400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shop',
            name='fit',
            field=models.CharField(default=1, max_length=400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shop',
            name='neck',
            field=models.CharField(default=1, max_length=400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shop',
            name='occasion',
            field=models.CharField(default=1, max_length=400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shop',
            name='sleeve',
            field=models.CharField(default=1, max_length=400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shop',
            name='wash_care',
            field=models.CharField(default=1, max_length=400),
            preserve_default=False,
        ),
    ]
