# Generated by Django 5.0.7 on 2024-09-04 22:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0023_shop_design_shop_fit_shop_neck_shop_occasion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
