# Generated by Django 5.0.7 on 2024-09-04 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0024_shop_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='design',
        ),
        migrations.RemoveField(
            model_name='product',
            name='fit',
        ),
        migrations.RemoveField(
            model_name='product',
            name='neck',
        ),
        migrations.RemoveField(
            model_name='product',
            name='occasion',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sleeve',
        ),
        migrations.RemoveField(
            model_name='product',
            name='wash_care',
        ),
    ]
