# Generated by Django 5.0.7 on 2024-09-06 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0028_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
