# Generated by Django 5.0.7 on 2024-09-13 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0035_orderdesign'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderdesign',
            old_name='price',
            new_name='amount',
        ),
    ]
