# Generated by Django 5.0.7 on 2024-09-13 18:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0037_ordercart_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdesign',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
