# Generated by Django 5.0.7 on 2024-09-18 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0038_orderdesign_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordercart',
            name='delivered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ordercart',
            name='order_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ordercart',
            name='shipped',
            field=models.BooleanField(default=False),
        ),
    ]
