# Generated by Django 5.0.7 on 2024-09-18 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0040_orderdesign_delivered_orderdesign_order_confirmed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordercart',
            name='order_confirmed',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='orderdesign',
            name='order_confirmed',
            field=models.BooleanField(default=True),
        ),
    ]
